version: "3"

services:
  hello-world:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8090:8080"
    deploy:
      mode: replicated
      replicas: 1